"""add metric and metric_def

Revision ID: 4de188592eb5
Revises: a70937427207
Create Date: 2026-08-08 08:59:02.444916

Tall storage for anything measurable, replacing the wide `body_composition`
table whose nine columns include five that have never held a value.

`document_id` from the design (docs/plans/0003-units-and-metrics.md §3) is
deliberately omitted: the `document` table does not exist until Plan 0005, and
with foreign_keys=ON a reference to a missing table fails at INSERT, not at
CREATE. It is added when its target exists.

No data moves here - the backfill is the next revision.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4de188592eb5'
down_revision: str | Sequence[str] | None = 'a70937427207'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# (name, canonical_unit, description, ref_low, ref_high)
METRIC_DEFS = [
    # Produced by openScale today. These four are exactly the columns of
    # body_composition that are ever populated.
    ("body_weight_lb", "lb", "Total body mass. Pounds are canonical (ADR-0003).", None, None),
    ("body_fat_pct", "%", "Body fat as a percentage of total mass.", None, None),
    (
        "muscle_pct",
        "%",
        "Muscle as a percentage of total mass. NOT a mass - the legacy column "
        "body_composition.muscle_mass is misnamed; the rename happens here.",
        None,
        None,
    ),
    ("water_pct", "%", "Total body water as a percentage of total mass.", None, None),
    # Declared now, populated later. metric_def is a vocabulary, not storage, so
    # this costs nothing and fixes names and units before anything writes them.
    # v_metric_coverage reports n_rows = 0 so an agent can tell "never recorded"
    # from "recorded and unchanged".
    ("alcohol_units", "units", "Standard drinks. Log 0 on dry days so streaks compute from data rather than from absence.", None, None),
    ("mood", "1-10", "Self-reported mood.", 1, 10),
    ("sleep_hours", "hours", "Hours slept.", None, None),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_def',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('canonical_unit', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ref_low', sa.Float(), nullable=True),
    sa.Column('ref_high', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=10), sa.Computed('substr(observed_at, 1, 10)', persisted=True), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.CheckConstraint('value IS NOT NULL OR text_value IS NOT NULL', name='ck_metric_has_a_value'),
    sa.ForeignKeyConstraint(['name'], ['metric_def.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observed_at', 'name', 'source', name='uq_metric_observation')
    )
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.create_index('ix_metric_date_name', ['date', 'name'], unique=False)

    # ### end Alembic commands ###

    op.bulk_insert(
        sa.table(
            "metric_def",
            sa.column("name", sa.String),
            sa.column("canonical_unit", sa.String),
            sa.column("description", sa.Text),
            sa.column("ref_low", sa.Float),
            sa.column("ref_high", sa.Float),
        ),
        [
            {
                "name": name,
                "canonical_unit": unit,
                "description": description,
                "ref_low": ref_low,
                "ref_high": ref_high,
            }
            for name, unit, description, ref_low, ref_high in METRIC_DEFS
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.drop_index('ix_metric_date_name')

    op.drop_table('metric')
    op.drop_table('metric_def')
    # ### end Alembic commands ###
