"""baseline existing schema

Revision ID: ac2fc3529985
Revises:
Create Date: 2026-08-08 08:07:28.323555

The schema as it stood when Alembic was adopted, captured in full so that a
fresh database can be built from nothing by `upgrade head`.

Databases that predate Alembic already have every one of these tables. They are
brought into the migration history with `alembic stamp ac2fc3529985`, which
records the revision as applied WITHOUT running it. Running it against an
existing database would fail on the first CREATE TABLE. `init_db()` performs
that stamp automatically (see app/database.py).

This revision also subsumes the hand-rolled `migrations/add_exercise_notes.py`:
`exercises.notes` is part of the baseline, so the standalone script is gone.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac2fc3529985'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_composition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('weight_unit', sa.String(length=8), nullable=False),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('muscle_mass', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('water_pct', sa.Float(), nullable=True),
    sa.Column('bone_mass', sa.Float(), nullable=True),
    sa.Column('visceral_fat', sa.Float(), nullable=True),
    sa.Column('metabolic_age', sa.Integer(), nullable=True),
    sa.Column('protein_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp')
    )
    with op.batch_alter_table('body_composition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_composition_date'), ['date'], unique=False)
        batch_op.create_index('ix_body_composition_date_timestamp', ['date', 'timestamp'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_used', sa.String(length=10), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_last_used'), ['last_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=True)

    op.create_table('upcoming_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=16), nullable=False),
    sa.Column('reps', sa.String(length=16), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('distance_unit', sa.String(length=16), nullable=True),
    sa.Column('time', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upcoming_workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upcoming_workouts_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upcoming_workouts_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upcoming_workouts_session'), ['session'], unique=False)

    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=16), nullable=False),
    sa.Column('reps', sa.String(length=16), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('distance_unit', sa.String(length=16), nullable=True),
    sa.Column('time', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workouts_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workouts_date'), ['date'], unique=False)
        batch_op.create_index('ix_workouts_date_order', ['date', 'order'], unique=False)
        batch_op.create_index(batch_op.f('ix_workouts_exercise_id'), ['exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workouts_exercise_id'))
        batch_op.drop_index('ix_workouts_date_order')
        batch_op.drop_index(batch_op.f('ix_workouts_date'))
        batch_op.drop_index(batch_op.f('ix_workouts_category_id'))

    op.drop_table('workouts')
    with op.batch_alter_table('upcoming_workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upcoming_workouts_session'))
        batch_op.drop_index(batch_op.f('ix_upcoming_workouts_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_upcoming_workouts_category_id'))

    op.drop_table('upcoming_workouts')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_name'))
        batch_op.drop_index(batch_op.f('ix_exercises_last_used'))

    op.drop_table('exercises')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    with op.batch_alter_table('body_composition', schema=None) as batch_op:
        batch_op.drop_index('ix_body_composition_date_timestamp')
        batch_op.drop_index(batch_op.f('ix_body_composition_date'))

    op.drop_table('body_composition')
    # ### end Alembic commands ###
