"""reps to integer

Revision ID: fd709c41eb19
Revises: ac2fc3529985
Create Date: 2026-08-08 08:14:26.876851

`reps` was TEXT solely to hold AMRAP notation like "5+". Nothing ever wrote one:
zero of 9,252 non-null values across eight years of history contain a "+", and
none are non-numeric. Meanwhile every numeric query on the column was silently
wrong, because text comparison is lexicographic - `WHERE reps > 3` excludes "10".

See ADR-0005. AMRAP now belongs to the Liftoscript parser, which resolves "5+"
into an integer plus an "AMRAP" comment at parse time.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fd709c41eb19'
down_revision: str | Sequence[str] | None = 'ac2fc3529985'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = ("workouts", "upcoming_workouts")


def _guard_non_integer_reps() -> None:
    """Refuse to migrate if any value would not survive the rebuild.

    The batch rebuild copies rows into a table whose `reps` has INTEGER
    affinity. Affinity converts "5" to 5, but a value SQLite cannot losslessly
    convert - "5+" - is simply stored as TEXT in the new column, leaving a
    string in a column everything downstream now assumes is numeric. No error is
    raised either way, so the check has to happen here.

    The losslessness verified during planning is a property of the data at that
    moment, not a guarantee. One AMRAP row entered since would invalidate it.
    """
    conn = op.get_bind()
    for table in TABLES:
        bad = conn.execute(
            sa.text(
                f"SELECT count(*) FROM {table} "  # noqa: S608 - fixed identifiers
                "WHERE reps IS NOT NULL AND CAST(reps AS INTEGER) || '' <> reps"
            )
        ).scalar()
        if bad:
            samples = conn.execute(
                sa.text(
                    f"SELECT DISTINCT reps FROM {table} "  # noqa: S608
                    "WHERE reps IS NOT NULL AND CAST(reps AS INTEGER) || '' <> reps LIMIT 5"
                )
            ).scalars().all()
            raise RuntimeError(
                f"{table}: {bad} row(s) have non-integer reps and would be corrupted "
                f"by this migration. Examples: {samples}. Resolve them first - move "
                f"the notation into `comment` and leave an integer in `reps`."
            )


def upgrade() -> None:
    """Upgrade schema."""
    _guard_non_integer_reps()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upcoming_workouts', schema=None) as batch_op:
        batch_op.alter_column('reps',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('reps',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('reps',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('upcoming_workouts', schema=None) as batch_op:
        batch_op.alter_column('reps',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
